### ISSUE TITLE
duvida ekf_localization

### ISSUE THREAD

**Issue by vilmaneves** [guilhermelawless/turtlebot3_datasets#1]
Boa tarde,
Quando faço launch ao ekf_localization.launch no terminal, aparece-me "ERROR: cannot launch node of type [ekf_localization/ekf_localization_node]: can't locate node [ekf_localization_node] in package [ekf_localization]"
Não percebo qual a razão, já alterei o ekf_localization.launch
E o CmakeList também me parece estar bem . Estou a fazer alguma coisa mal?

![screenshot from 2018-11-01 17-55-07](https://user-images.githubusercontent.com/22432164/47869830-da14df00-ddff-11e8-956e-89671515cb27.png)
![screenshot from 2018-11-01 17-54-41](https://user-images.githubusercontent.com/22432164/47869831-da14df00-ddff-11e8-9cf9-5cdb828aa5fe.png)
![screenshot from 2018-11-01 17-53-51](https://user-images.githubusercontent.com/22432164/47869832-da14df00-ddff-11e8-9aa8-651454a568a0.png)

Obrigada desde já

**Comment by guilhermelawless** [comment]
O código já foi compilado? `catkin_make`. Após a primeira compilação, é também necessário `souce ~/.bashrc`

**Comment by vilmaneves** [comment]
Quando faço catkin_make dá me erro de dependencia. Não perceboa razao deste erro
![screenshot from 2018-11-02 10-30-35](https://user-images.githubusercontent.com/22432164/47910350-813e5880-de8a-11e8-98e8-af14a68f7ff8.png)

![screenshot from 2018-11-02 10-30-54](https://user-images.githubusercontent.com/22432164/47910371-92876500-de8a-11e8-82a6-d38b32856f83.png)

**Comment by guilhermelawless** [comment]
Essa linha está comentada no ficheiro original, deves ter descomentado acidentalmente.

Fiz updates ao código para ser mais funcional _by default_ . Ver [aqui](https://github.com/guilhermelawless/ekf_localization/commits/master) os últimos commits.

Neste momento já corre _as is_, mas vão precisar de alterar parâmetros.

**Comment by vilmaneves** [comment]
Já consegui correr o launch e abrir o mapa no rviz mas com o launch antigo que usa as bags. Com o novo launch diz que nao encontra o mapa. Obrigada

**Comment by guilhermelawless** [comment]
De nada, mas aconselho a usar o novo launch modificando apenas a linha do map_file [aqui](https://github.com/guilhermelawless/ekf_localization/blob/master/launch/ekf_localization.launch#L5)

**Comment by VascoNunes** [comment]
![image](https://user-images.githubusercontent.com/22856608/47966936-84367600-e04f-11e8-97d3-70a8dfa16411.png)

Com o novo launch file o problema de encontrar o mapa desapareceu pois aparece no rviz. Agora estou a ter este erro estranho. 

Penso que seja suposto correr este launch file e  o bag ao mesmo tempo agora certo?
Se for assim, que cuidados devemos ter?

E quanto aos parametros no ficheiro yaml que temos de mexer, há alguma documentaçao a explicar o que cada um faz? Tentei ir ao link que aparece no ficheiro mas aparentemente o site está em baixo.

**Comment by guilhermelawless** [comment]
Sim, a bag em separado. O melhor é lançar o algoritmo primeiro e só depois a bag. Esse erro aparece quando o algoritmo não "vê" as static TFs que aparecem logo no início da bag

**Comment by VascoNunes** [comment]
Tentei isso, mas continua com o mesmo erro dps de lançar a bag com rosbag play --clock 
É suposto comentar o parâmetro de sim_time no launch file do ekf certo?

**Comment by guilhermelawless** [comment]
Posso ir ao laboratório amanhã de manhã, envia-me um e-mail por favor (está no meu profile)

**Comment by guilhermelawless** [comment]
O parâmetro sim_time tem de estar ativo (True)

**Comment by fsousa96** [comment]
Boas, 
Qnd estamos a utilizar o amcl o costmap tem de ser utilizado?
![image](https://user-images.githubusercontent.com/36681839/48158700-18f8d800-e2cb-11e8-830e-40c4b375c256.png)
O nosso está com warning e diz que No map received!

O algoritmo como temos agora depois de perceber que está num determinado sitio nunca volta a disperçar os pontos mesmo quando claramente as paredes nao coincidem com o laser.
Obrigado

**Comment by guilhermelawless** [comment]
Esses tópicos referem-se ao move_base que é parte do navigation stack para o robô se mover de um ponto para outro.

O amcl apenas fornece a localização do robô. Que passos estão a seguir? Sugiro iniciar o amcl e começar uma nova configuração do rviz em que adicionam manualmente os tópicos que querem.

Além disso, ativar aí os tópicos/mapa/etc apenas faz com que os possas visualizar, não controla a source.
